trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

variables:
  ArtifactPath: 'C:\Users\mafia\Downloads\vsts-agent-win-x64-3.248.0\_work\1\a\app.zip'

steps:

# Step 1: Set execution policy to bypass
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process'
  displayName: 'Set Execution Policy to Bypass'

# Step 2: Install dependencies
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
  displayName: 'Set up Python 3.9'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

# Step 3: Archive the application
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive Application'

# Step 4: Publish the artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

# Step 5: Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ScannerAppConnection'
    appType: 'webApp'
    appName: 'ScannerApp'
    package: '$(ArtifactPath)'
  displayName: 'Deploy Flask App to Azure'

