trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

steps:

# Step 1: Set up Python 3.9
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
  displayName: 'Set up Python 3.9'

# Step 2: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

# Step 3: Deploy Flask app to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ScannerAppConnection'
    appType: 'webApp'  
    appName: 'ScannerApp'
    package: $(System.DefaultWorkingDirectory)
  displayName: 'Deploy Flask App to Azure'

# Step 4: Initialize Database
- script: python init_db.py
  displayName: 'Initialize Database'
