trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

steps:

# Step 1: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

# Step 3: Create ZIP File of Build Output Using 7-Zip
- script: |
    mkdir $(Build.ArtifactStagingDirectory)
    7z a $(Build.ArtifactStagingDirectory)\app.zip $(System.DefaultWorkingDirectory)\* || exit 0
  displayName: 'Create ZIP File of Build Output Using 7-Zip'

# Step 4: Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

