trigger:
  branches:
    include:
      - main  # Trigger pipeline on pushes to the main branch

pool:
  name: 'Default'  # Use the provided pool configuration

steps:

# Step 1: Set execution policy to bypass (only for Windows agents)
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process'
  displayName: 'Set Execution Policy to Bypass'

# Step 2: Install Python dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

# Step 3: Initialize Database
- script: |
    echo "Initializing the database..."
    python init_db.py
  displayName: 'Initialize Database'
  env:
    MYSQL_USERNAME: $(AZURE_MYSQL_USER)
    MYSQL_PASSWORD: $(AZURE_MYSQL_PASSWORD)
    MYSQL_HOST: $(AZURE_MYSQL_HOST)
    MYSQL_DATABASE: $(AZURE_MYSQL_NAME)

# Step 4: Deploy Flask app to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ScannerAppConnection'  # Azure DevOps service connection
    appType: 'webApp'
    appName: 'ScannerApp'  # Azure App Service name
    package: $(System.DefaultWorkingDirectory)
  displayName: 'Deploy Flask App to Azure'
