trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

steps:

# Step 1: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python Dependencies'

# Step 2: Create ZIP package
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive application files'

# Step 3: Publish artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

# Step 4: Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'ScannerAppConnection'  # Azure DevOps service connection
    appType: 'webApp'
    appName: 'ScannerApp'  # Azure App Service name
    package: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Deploy Flask App to Azure'
